# Generated by Django 5.2.1 on 2025-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_time',
            field=models.JSONField(null=True),
        ),
    ]
