# Generated by Django 5.2.1 on 2025-05-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0003_alter_user_available_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.JSONField(blank=True, null=True)),
                ('personal_select_days', models.JSONField(blank=True, null=True)),
                ('group_select_days_level1', models.JSONField(blank=True, null=True)),
                ('group_select_time_level1', models.JSONField(blank=True, null=True)),
                ('group_capacity_level1', models.PositiveIntegerField(blank=True, null=True)),
                ('group_select_days_level2', models.JSONField(blank=True, null=True)),
                ('group_select_time_level2', models.JSONField(blank=True, null=True)),
                ('group_capacity_level2', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10)),
                ('group_trainer_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_trainer_1_programs', to=settings.AUTH_USER_MODEL)),
                ('group_trainer_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_trainer_2_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
