# Generated by Django 5.2.1 on 2025-05-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0004_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('interested', 'Interested'), ('converted', 'Converted'), ('inactive', 'Inactive')], max_length=20)),
                ('new_client', models.BooleanField(default=True)),
                ('diet_first_consultation', models.BooleanField(default=False)),
                ('trainer_first_consultation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_group_time', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='frontline_backend.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_clients', to='frontline_backend.program')),
            ],
        ),
    ]
