# Generated by Django 5.2.1 on 2025-05-23 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0006_consulationschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulationschedules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
