# Generated by Django 5.2.1 on 2025-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0007_consulationschedules_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='diet_first_consultation',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='trainer_first_consultation',
            field=models.IntegerField(default=False),
        ),
    ]
