# Generated by Django 5.2.1 on 2025-05-23 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0008_alter_client_diet_first_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_consultation', models.IntegerField()),
                ('current_acitivity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('current_workouts', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_limitations', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_owned', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
