# Generated by Django 5.2.1 on 2025-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0009_trainerconsultationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
