# Generated by Django 5.2.1 on 2025-05-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0010_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
