# Generated by Django 5.2.1 on 2025-05-28 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0011_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='group_capacity_level3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='group_select_days_level3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='group_select_time_level3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='group_trainer_level3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_trainer_3_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
