# Generated by Django 5.2.1 on 2025-06-02 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0012_program_group_capacity_level3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programclient',
            name='dietitian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietitian_program_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programclient',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_program_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
