# Generated by Django 5.2.1 on 2025-06-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0013_programclient_dietitian_programclient_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='workout_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
