# Generated by Django 5.2.1 on 2025-06-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0014_client_workout_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWorkoutUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(blank=True, default=1)),
                ('no_of_days', models.IntegerField(blank=True, default=1)),
                ('week_start_date', models.DateField(null=True)),
                ('week_end_date', models.DateField(null=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyWorkoutwithDaysUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(blank=True, default=1)),
                ('day_no', models.IntegerField(blank=True, default=1)),
                ('workout_date', models.DateField(null=True)),
                ('workout_type', models.CharField(blank=True, max_length=100, null=True)),
                ('workout_sets', models.IntegerField(blank=True, default=1)),
                ('workout_reps', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
