# Generated by Django 5.2.1 on 2025-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0015_weeklyworkoutupdates_weeklyworkoutwithdaysupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='programclient',
            name='workout_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
