# Generated by Django 5.2.1 on 2025-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0016_programclient_workout_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyworkoutupdates',
            name='week_no_of_days',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
