# Generated by Django 5.2.1 on 2025-06-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0017_weeklyworkoutupdates_week_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyworkoutwithdaysupdates',
            name='weekly_updates_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.weeklyworkoutupdates'),
        ),
    ]
