# Generated by Django 5.2.1 on 2025-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0018_weeklyworkoutwithdaysupdates_weekly_updates_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyworkoutupdates',
            name='week_workout_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyworkoutupdates',
            name='week_workout_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
