# Generated by Django 5.2.1 on 2025-06-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0019_weeklyworkoutupdates_week_workout_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyworkoutwithdaysupdates',
            name='weekly_updates_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts', to='frontline_backend.weeklyworkoutupdates'),
        ),
    ]
