# Generated by Django 5.2.1 on 2025-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0020_alter_weeklyworkoutwithdaysupdates_weekly_updates_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programclient',
            name='program_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
