# Generated by Django 5.2.1 on 2025-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0022_clienattendanceupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programclient',
            name='preferred_time',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
