# Generated by Django 5.2.1 on 2025-06-14 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0023_alter_programclient_preferred_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='New Lead', max_length=10, null=True)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('program_name', models.CharField(max_length=255)),
                ('preferred_days', models.JSONField(blank=True, null=True)),
                ('preferred_time', models.JSONField(blank=True, null=True)),
                ('lead_date', models.DateField(null=True)),
                ('follow_up_date', models.DateField(null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
