# Generated by Django 5.2.1 on 2025-06-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0025_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.country'),
        ),
    ]
