# Generated by Django 5.2.1 on 2025-06-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0027_leadsfollowup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsfollowup',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='leadsfollowup',
            old_name='sales_id',
            new_name='sales',
        ),
    ]
