# Generated by Django 5.2.1 on 2025-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0028_rename_lead_id_leadsfollowup_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsfollowup',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
