# Generated by Django 5.2.1 on 2025-06-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0030_client_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role_assigned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
