# Generated by Django 5.2.1 on 2025-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0031_client_role_assigned_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsfollowup',
            name='activity_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
