# Generated by Django 5.2.1 on 2025-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0032_leadsfollowup_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsfollowup',
            name='lead_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadsfollowup',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
