# Generated by Django 5.2.1 on 2025-06-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0033_leadsfollowup_lead_status_leadsfollowup_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='notes',
        ),
        migrations.AddField(
            model_name='leads',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
