# Generated by Django 5.2.1 on 2025-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0034_remove_leads_notes_leads_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(default='New Lead', max_length=255, null=True),
        ),
    ]
