# Generated by Django 5.2.1 on 2025-06-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0036_client_amount_client_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client'),
        ),
    ]
