# Generated by Django 5.2.1 on 2025-06-28 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0037_leads_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_consultation', models.IntegerField()),
                ('diet_preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('current_eating_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('appetite_level', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_meals_per_day', models.CharField(blank=True, max_length=100, null=True)),
                ('cook_at_home_out', models.CharField(blank=True, max_length=100, null=True)),
                ('food_allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_before', models.CharField(blank=True, max_length=100, null=True)),
                ('snacking_habits', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrient_deficiencies', models.CharField(blank=True, max_length=100, null=True)),
                ('sleeping_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('water_intake_per_day', models.CharField(blank=True, max_length=100, null=True)),
                ('working_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('stress', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_time', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_existing_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('past_surgeries', models.CharField(blank=True, max_length=100, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('menstrual_history', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnancy_history', models.CharField(blank=True, max_length=100, null=True)),
                ('breast_feeding', models.CharField(blank=True, max_length=100, null=True)),
                ('supplements', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_tests', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
