# Generated by Django 5.2.1 on 2025-07-02 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0039_weeklydietupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDietConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, default=1)),
                ('consult_date', models.DateField(null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('dietitian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
