# Generated by Django 5.2.1 on 2025-07-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0040_monthlydietconsultationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydietconsultationdetails',
            name='consult_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.consulationschedules'),
        ),
    ]
