# Generated by Django 5.2.1 on 2025-07-03 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0041_monthlydietconsultationdetails_consult_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiweeklyUpdations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(blank=True, default=1)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=0)),
                ('update_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('dietitian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
