# Generated by Django 5.2.1 on 2025-07-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0042_biweeklyupdations'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='program_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='program_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_months', models.IntegerField(default=3)),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('program_end_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_type', models.CharField(default='new', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.program')),
            ],
        ),
    ]
