# Generated by Django 5.2.1 on 2025-07-05 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0043_client_program_end_date_client_program_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingsTDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(default='day_1', max_length=120)),
                ('day_no', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('actual_meeting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('dietitian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_dietitian', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
