# Generated by Django 5.2.1 on 2025-07-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0044_meetingstdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTDCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('change_dietplan', models.BooleanField(default=0)),
                ('uploaded', models.BooleanField(default=0)),
                ('diet_paln', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_plan_uploaded_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meetingtdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.meetingstdc')),
            ],
        ),
    ]
