# Generated by Django 5.2.1 on 2025-07-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0045_meetingtdcdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurementsclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('right_arm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('left_arm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('hip', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('left_thigh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('right_thigh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('right_calf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('left_calf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meetingtdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.meetingstdc')),
            ],
        ),
    ]
