# Generated by Django 5.2.1 on 2025-07-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0046_measurementsclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstdc',
            name='need_meeting',
            field=models.BooleanField(default=1),
        ),
    ]
