# Generated by Django 5.2.1 on 2025-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0047_meetingstdc_need_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingstdc',
            name='need_meeting',
            field=models.IntegerField(default=1),
        ),
    ]
