# Generated by Django 5.2.1 on 2025-07-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0048_alter_meetingstdc_need_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstdc',
            name='measurements',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='WeeklyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('week_no', models.IntegerField(default=1)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('entered_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('dietitian_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
