# Generated by Django 5.2.1 on 2025-07-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0049_meetingstdc_measurements_weeklymeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymeeting',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
