# Generated by Django 5.2.1 on 2025-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0050_weeklymeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsclients',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
