# Generated by Django 5.2.1 on 2025-07-08 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0051_measurementsclients_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='subscription_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='ClientPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=120, null=True)),
                ('type', models.CharField(default='Paused', max_length=120, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_from', models.DateField(blank=True, null=True)),
                ('paused_to', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPauseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_months', models.IntegerField(default=1, null=True)),
                ('no_of_days_available', models.IntegerField(default=0, null=True)),
                ('no_of_pauses_available', models.IntegerField(default=0, null=True)),
                ('no_of_paused_days', models.IntegerField(default=0, null=True)),
                ('no_of_pauses_taken', models.IntegerField(default=0, null=True)),
                ('no_of_pause_days_rem', models.IntegerField(default=0, null=True)),
                ('no_of_pause_rem', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
            ],
        ),
    ]
