# Generated by Django 5.2.1 on 2025-07-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0052_clientsubscription_subscription_id_clientpause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='subscription_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
