# Generated by Django 5.2.1 on 2025-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0053_alter_clientsubscription_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_months', models.IntegerField(default=1, null=True)),
                ('no_of_pauses', models.IntegerField(default=0, null=True)),
                ('no_of_days', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
