# Generated by Django 5.2.1 on 2025-07-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0054_subscriptionpause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpause',
            old_name='no_of_pauses',
            new_name='no_of_pause',
        ),
    ]
