# Generated by Django 5.2.1 on 2025-07-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0055_rename_no_of_pauses_subscriptionpause_no_of_pause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpause',
            old_name='no_of_pause',
            new_name='no_of_pauses',
        ),
    ]
