# Generated by Django 5.2.1 on 2025-07-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0056_rename_no_of_pause_subscriptionpause_no_of_pauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='program_type',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
