# Generated by Django 5.2.1 on 2025-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0057_clientsubscription_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='program_type',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
