# Generated by Django 5.2.1 on 2025-07-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0058_alter_clientsubscription_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
