# Generated by Django 5.2.1 on 2025-07-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0059_client_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpause',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
