# Generated by Django 5.2.1 on 2025-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0060_clientpause_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpause',
            name='program_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientpause',
            name='program_end_date_changed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
