# Generated by Django 5.2.1 on 2025-07-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0061_clientpause_program_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpause',
            name='program_pause_reactivate_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
