# Generated by Django 5.2.1 on 2025-07-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0062_clientpause_program_pause_reactivate_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietchartClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.BooleanField(default=0)),
                ('diet_paln', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_plan_uploaded_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
