# Generated by Django 5.2.1 on 2025-07-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0063_dietchartclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietchartclient',
            old_name='diet_paln',
            new_name='diet_plan',
        ),
    ]
