# Generated by Django 5.2.1 on 2025-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0064_rename_diet_paln_dietchartclient_diet_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietchartclient',
            name='diet_plan',
            field=models.FileField(null=True, upload_to='diet_chart/'),
        ),
    ]
