# Generated by Django 5.2.1 on 2025-07-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0065_alter_dietchartclient_diet_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpause',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
