# Generated by Django 5.2.1 on 2025-07-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0066_clientpause_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstdc',
            name='dietitian_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingstdc',
            name='meeting_for',
            field=models.CharField(default='both', max_length=120),
        ),
        migrations.AddField(
            model_name='meetingstdc',
            name='trainer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrainerMeetingTDCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_sit_up', models.CharField(default=True, max_length=255, null=True)),
                ('modified_push_ups', models.CharField(default=True, max_length=255, null=True)),
                ('plank_hold', models.CharField(default=True, max_length=255, null=True)),
                ('wall_sqaut_hold', models.CharField(default=True, max_length=255, null=True)),
                ('shoulder_flexibility', models.CharField(default=True, max_length=255, null=True)),
                ('sit_and_reach', models.CharField(default=True, max_length=255, null=True)),
                ('hamstring_flexibility', models.CharField(default=True, max_length=255, null=True)),
                ('quadriceps_flexibility', models.CharField(default=True, max_length=255, null=True)),
                ('rounded_shoulder', models.CharField(default=True, max_length=255, null=True)),
                ('kyphosis', models.CharField(default=True, max_length=255, null=True)),
                ('lordosis', models.CharField(default=True, max_length=255, null=True)),
                ('scoliosis', models.CharField(default=True, max_length=255, null=True)),
                ('bow_leg', models.CharField(default=True, max_length=255, null=True)),
                ('knock_knees', models.CharField(default=True, max_length=255, null=True)),
                ('winging_of_scapula', models.CharField(default=True, max_length=255, null=True)),
                ('flat_foot', models.CharField(default=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meetingtdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.meetingstdc')),
            ],
        ),
    ]
