# Generated by Django 5.2.1 on 2025-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0067_meetingstdc_dietitian_status_meetingstdc_meeting_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermeetingtdcdetails',
            name='need_data',
            field=models.BooleanField(default=False),
        ),
    ]
