# Generated by Django 5.2.1 on 2025-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0068_trainermeetingtdcdetails_need_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstdc',
            name='trainer_actual_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
