# Generated by Django 5.2.1 on 2025-07-22 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0069_meetingstdc_trainer_actual_meeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReschedulesSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=55, null=True)),
                ('reschedule', models.BooleanField(default=True)),
                ('reschedule_to', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('trainer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
