# Generated by Django 5.2.1 on 2025-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0070_reschedulessessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=1)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
