# Generated by Django 5.2.1 on 2025-07-29 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0071_mainprogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='group_capacity_level1',
            new_name='program_capacity',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='group_select_days_level1',
            new_name='program_select_days',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='group_select_days_level2',
            new_name='program_select_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_capacity_level2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_capacity_level3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_select_days_level3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_select_time_level1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_select_time_level2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_select_time_level3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_trainer_level1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_trainer_level2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group_trainer_level3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='personal_select_days',
        ),
        migrations.AddField(
            model_name='program',
            name='mainprogram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mainprograms', to='frontline_backend.mainprogram'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
