# Generated by Django 5.2.1 on 2025-07-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0072_rename_group_capacity_level1_program_program_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
