# Generated by Django 5.2.1 on 2025-08-02 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0073_program_created_at_program_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leads',
            name='sales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
