# Generated by Django 5.2.1 on 2025-08-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0074_leads_trainer_alter_leads_sales_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.country'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='frontline_backend.client'),
        ),
    ]
