# Generated by Django 5.2.1 on 2025-08-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0075_client_country_alter_leads_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
    ]
