# Generated by Django 5.2.1 on 2025-08-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0076_client_age_leads_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
