# Generated by Django 5.2.1 on 2025-08-10 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0077_leads_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstdc',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='Renewal', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('actual_completion_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ClientPause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.clientpause')),
                ('LeadsFollowup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.leadsfollowup')),
                ('MeetingsTDC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.meetingstdc')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_as_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
