# Generated by Django 5.2.1 on 2025-08-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0078_meetingstdc_sales_dailytasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingstdc',
            name='sales',
        ),
    ]
