# Generated by Django 5.2.1 on 2025-08-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0079_remove_meetingstdc_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytasks',
            old_name='sales',
            new_name='User',
        ),
    ]
