# Generated by Django 5.2.1 on 2025-08-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0080_rename_sales_dailytasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
