# Generated by Django 5.2.1 on 2025-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0081_alter_dailytasks_actual_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='postponed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
