# Generated by Django 5.2.1 on 2025-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0082_dailytasks_postponed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='bow_leg',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='flat_foot',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='half_sit_up',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='hamstring_flexibility',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='knock_knees',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='kyphosis',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='lordosis',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='modified_push_ups',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='plank_hold',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='quadriceps_flexibility',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='rounded_shoulder',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='scoliosis',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='shoulder_flexibility',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='sit_and_reach',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='wall_sqaut_hold',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerconsultationdetails',
            name='winging_of_scapula',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
