# Generated by Django 5.2.1 on 2025-08-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0083_trainerconsultationdetails_bow_leg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=True)),
                ('session_date', models.DateField(null=True)),
                ('completed_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
            ],
        ),
    ]
