# Generated by Django 5.2.1 on 2025-08-23 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0084_client_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='User',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_as_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
