# Generated by Django 5.2.1 on 2025-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0085_client_sessions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client_sessions',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
