# Generated by Django 5.2.1 on 2025-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0086_client_sessions_canceled_client_sessions_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='canceled_by',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
