# Generated by Django 5.2.1 on 2025-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0087_client_sessions_canceled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='program_type',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
