# Generated by Django 5.2.1 on 2025-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0088_client_sessions_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='group_attendance',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
