# Generated by Django 5.2.1 on 2025-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0089_client_sessions_group_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_consulation_date_dietitian',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_consulation_date_trainer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
