# Generated by Django 5.2.1 on 2025-09-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0090_client_first_consulation_date_dietitian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='WeeklyMeeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.weeklymeeting'),
        ),
    ]
