# Generated by Django 5.2.1 on 2025-09-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0091_dailytasks_weeklymeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_leave_capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('program_end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=2)),
                ('rem_cancel', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontline_backend.client')),
            ],
        ),
    ]
