# Generated by Django 5.2.1 on 2025-09-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0092_client_leave_capacity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client_leave_capacity',
            new_name='ClientCancel',
        ),
    ]
