# Generated by Django 5.2.1 on 2025-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontline_backend', '0093_rename_client_leave_capacity_clientcancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sessions',
            name='reschuled',
            field=models.BooleanField(default=False),
        ),
    ]
